### ISSUE TITLE
Writing log gives permission denied error

### ISSUE THREAD

**Issue by rikuson** [savercorp/docker-janus-cloud#3]
```
Janus-sentinel loads the config file: /opt/janus-cloud/conf/janus-sentinel.yml                                                                                                                                  
Traceback (most recent call last):                                                                                                                                                                              
  File "/usr/local/bin/janus-sentinel", line 8, in <module>                                                                                                                                                     
    sys.exit(main())                                                                                                                                                                                            
  File "/usr/local/lib/python3.8/dist-packages/januscloud/sentinel/main.py", line 27, in main                                                                                                                   
    do_main(config)                                                                                                                                                                                             
  File "/usr/local/lib/python3.8/dist-packages/januscloud/sentinel/main.py", line 45, in do_main
    set_root_logger(**(config['log']))
  File "/usr/local/lib/python3.8/dist-packages/januscloud/common/logger.py", line 43, in set_root_logger 
    rfh = logging.handlers.RotatingFileHandler(log_to_file,
  File "/usr/lib/python3.8/logging/handlers.py", line 148, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.8/logging/handlers.py", line 55, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/log/janus-sentinel.log'
```

**Comment by rikuson** [comment]
Disable writing log file.
